# Generated by Django 5.2.10 on 2026-01-25 11:02

import django.db.models.deletion
import django.utils.timezone
import django_currentuser.db.models.fields
import django_currentuser.middleware
import chat.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique id')),
                ('_created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('_updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('_is_deleted', models.BooleanField(default=False)),
                ('_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('chat_type', models.CharField(choices=[('private', 'Private'), ('group', 'Group'), ('channel', 'Channel')], default='private', max_length=10)),
                ('_created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chats', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': '04-chat',
                'verbose_name_plural': '04-chats',
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='ChatMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique id')),
                ('_created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('_updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('_is_deleted', models.BooleanField(default=False)),
                ('_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is_admin')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='joined_at')),
                ('_created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_chat', to='ticket.chat', verbose_name='chat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_member', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': '05-member',
                'verbose_name_plural': '05-members',
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique id')),
                ('_created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('_updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('_is_deleted', models.BooleanField(default=False)),
                ('_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('voice', models.FileField(blank=True, null=True, upload_to='voice_messages/')),
                ('is_edited', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('_created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='ticket.chat', verbose_name='message')),
                ('forward_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwards', to='ticket.message')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='ticket.message')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sender', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': '06-chat_message',
                'verbose_name_plural': '06-chat_messages',
                'db_table': 'chat_message',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique id')),
                ('_created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('_updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('_is_deleted', models.BooleanField(default=False)),
                ('_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='upload_to_by_date', verbose_name='avatar')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='bio')),
                ('_created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_chat', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': '03-profile',
                'verbose_name_plural': '03-profile',
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique id')),
                ('_created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('_updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('_is_deleted', models.BooleanField(default=False)),
                ('_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=30)),
                ('number', models.CharField(default=chat.utils.generate_ticket_number, editable=False, max_length=256, unique=True, verbose_name='number')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='description')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='title')),
                ('is_active', models.BooleanField(default=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('can_reply', models.BooleanField(default=True)),
                ('can_upload_attachment', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, choices=[('technical', 'Technical'), ('course', 'Course'), ('mentoring', 'Mentoring')], max_length=400, null=True, verbose_name='category')),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('high', 'High'), ('force', 'Force')], max_length=400, null=True, verbose_name='priority')),
                ('is_pinned', models.BooleanField(default=False)),
                ('_created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': '01-ticket',
                'verbose_name_plural': '01-tickets',
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='TicketDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique id')),
                ('_created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('_updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('_is_deleted', models.BooleanField(default=False)),
                ('_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=1000, null=True, verbose_name='message')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=chat.utils.ticket_attachment_path, validators=[chat.utils.validate_attachment_file])),
                ('_created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('seen_by', models.ManyToManyField(blank=True, related_name='seen_ticket_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='ticket.ticket', verbose_name='detail_ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': '02-ticket_detail',
                'verbose_name_plural': '02-ticket_details',
                'db_table': 'ticket_detail',
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['creator', 'is_active'], name='chat_creator_d398b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatmembership',
            unique_together={('chat', 'user')},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['id'], name='ticket_id_72dc5c_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketdetail',
            index=models.Index(fields=['id'], name='ticket_deta_id_1cfec4_idx'),
        ),
    ]
