# Generated by Django 5.2.10 on 2026-01-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='voice',
            field=models.BinaryField(blank=True, null=True, verbose_name='voice'),
        ),
    ]
